### PR TITLE
Run pyupgrade to upgrade to more modern syntax

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
wazo-dist-upgrade must be the same version for stretch/buster/bullseye and f-string was not available on stretch (the OS version that the updated script will run)
For now, I would avoid any modification on this repo

**Comment by sopelj** [comment]
> wazo-dist-upgrade must be the same version for stretch/buster/bullseye and f-string was not available on stretch (the OS version that the updated script will run) For now, I would avoid any modification on this repo

This still runs on stretch? 😯

**Comment by fblackburn1** [comment]
> > wazo-dist-upgrade must be the same version for stretch/buster/bullseye and f-string was not available on stretch (the OS version that the updated script will run) For now, I would avoid any modification on this repo
> 
> This still runs on stretch? hushed

Yes [bin/wazo-dist-upgrade-buster-check](https://github.com/wazo-platform/wazo-dist-upgrade/pull/21/files#diff-2a9cf38e757908a056d04e72cc76c314aba84f78f569a94511b14786640f16ae) will run on stretch **before** to upgrade to buster

Also any modification to this repo need to be backported into all previous distributions

**Comment by sopelj** [comment]
> > > wazo-dist-upgrade must be the same version for stretch/buster/bullseye and f-string was not available on stretch (the OS version that the updated script will run) For now, I would avoid any modification on this repo
> > 
> > 
> > This still runs on stretch? hushed
> 
> Yes [bin/wazo-dist-upgrade-buster-check](https://github.com/wazo-platform/wazo-dist-upgrade/pull/21/files#diff-2a9cf38e757908a056d04e72cc76c314aba84f78f569a94511b14786640f16ae) will run on stretch **before** to upgrade to buster
> 
> Also any modification to this repo need to be backported into all previous distributions

Damn, that's old. Ok, sorry.

**Pull request closed without merging**
